modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/wafflecoffee/Empire-Minecraft-Utilities/issues"
license = "MIT"

[[mods]]
modId = "emcutils"
version = "${version}"
displayName = "Empire Minecraft Utilities"
authors = [
    "MrFrydae",
    "wafflecoffee",
    "BasiqueEvangelist",
    "BlockHead_56"
]
description = '''
A collection of various utilities for the Empire Minecraft server.
'''
logoFile = "icon.png"

[[dependencies.emcutils]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emcutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emcutils]]
modId = "architectury"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "CLIENT"