modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/wafflecoffee/Empire-Minecraft-Utilities/issues"
license = "MIT"

[[mods]]
modId = "emcutils"
version = "${version}+forge"
displayName = "Empire Minecraft Utilities"
authors = [
    "MrFrydae",
    "wafflecoffee",
    "BasiqueEvangelist",
    "BlockHead_56"
]
description = '''
A collection of various utilities for the Empire Minecraft server.
'''
logoFile = "icon.png"
updateJSONURL = "https://api.modrinth.com/updates/emcutils/forge_updates.json"

[[dependencies.emcutils]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emcutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emcutils]]
modId = "architectury"
mandatory = true
versionRange = "[3.5.12,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emcutils]]
modId = "configmenusforge"
mandatory = false
versionRange = "[3.1.0,)"
ordering = "NONE"
side = "CLIENT"