[versions]
minecraft = '1.19.3'

[libraries]
# MC, loaders, and mappings
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn = 'net.fabricmc:yarn:1.19.3+build.2' # https://fabricmc.net/develop
quilt_loader = 'org.quiltmc:quilt-loader:0.18.1-beta.22' # https://lambdaurora.dev/tools/import_quilt.html
forge = 'net.minecraftforge:forge:1.19.3-44.0.1' # https://files.minecraftforge.net/

# Dependencies for all subprojects
lombok = 'org.projectlombok:lombok:1.18.24' # https://mvnrepository.com/artifact/org.projectlombok/lombok
quiltflower = 'org.quiltmc:quiltflower:1.9.0' # https://maven.quiltmc.org/repository/release/org/quiltmc/quiltflower/

# Quilt subproject
quilted_fabric_api = 'org.quiltmc.quilted-fabric-api:quilted-fabric-api:5.0.0-alpha.2+0.68.1-1.19.3' # https://modrinth.com/mod/qsl
midnightlib = 'maven.modrinth:midnightlib:1.1.0-fabric' # https://modrinth.com/mod/midnightlib/versions
lazydfu = 'maven.modrinth:lazydfu:0.1.3' # https://modrinth.com/mod/lazydfu
modmenu = 'maven.modrinth:modmenu:5.0.0-alpha.4' # https://modrinth.com/mod/modmenu/versions

# Journey subproject
# https://jm.gserv.me/service/rest/repository/browse/maven-public/info/journeymap/journeymap-api/
journeymap_api = 'info.journeymap:journeymap-api:1.19.3-rc1-1.9-fabric-SNAPSHOT'
journeymap = 'maven.modrinth:journeymap:1.19.2-5.9.0beta3-fabric' # https://modrinth.com/mod/journeymap

# Xaero subproject
xaeros_minimap = 'curse.maven:xmm-263420:4127323' # https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap/files/all
xaeros_world_map = 'curse.maven:xwm-317780:4127339' # https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map/files/all

[plugins]
architectury_plugin = 'architectury-plugin:3.4.+'
architectury_loom = 'dev.architectury.loom:0.12.0.+'
loom_quiltflower = 'io.github.juuxel.loom-quiltflower:1.+'

machete = 'io.github.p03w.machete:1.+'
minotaur = 'com.modrinth.minotaur:2.+'
shadow = 'com.github.johnrengelman.shadow:7.+'
