modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/triphora/emcutils/issues"
license = "MIT"

[[mods]]
modId = "emcutils"
version = "${version}"
displayName = "Empire Minecraft Utilities"
authors = [
	"MrFrydae",
	"triphora",
	"BasiqueEvangelist",
	"BlockHead_56"
]
description = '''
A collection of various utilities for the Empire Minecraft server.
'''
logoFile = "emcutils.png"
updateJSONURL = "https://api.modrinth.com/updates/emcutils/forge_updates.json"

[[mixins]]
config = "emcutils-common.mixins.json"

[[dependencies.emcutils]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
side = "CLIENT"

[[dependencies.emcutils]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
side = "CLIENT"

[[dependencies.emcutils]]
modId = "configured"
type = "optional"
versionRange = "[2.5,)"
side = "CLIENT"
