name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - working-directory: fabric/
        run: curl -o voxelmap-1.18.1-1.10.20.jar https://cdn.discordapp.com/attachments/931521967385878559/932560873543835689/voxelmap-1.18.1-1.10.20.jar
      - run: ./gradlew build --no-daemon
