name: Release
on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - run: "./gradlew build :forge:modrinth :fabric:modrinth publish --no-daemon"
        env:
          MAVEN_URL: "https://maven.frydae.dev/releases"
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          SNAPSHOT: ""
