name: Release
on:
  workflow_dispatch:
    inputs:
      version_name:
        type: string
        description: Modrinth version name to use
        required: true
      changelog:
        type: string
        description: Modrinth changelog to use
        required: true
      version_type:
        type: choice
        description: Modrinth version type to use
        default: release
        options:
          - release
          - beta
          - alpha

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
          arguments: forge:modrinth fabric:modrinth
          cache-read-only: ${{ github.repository_owner != 'emmods' }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          VERSION_NAME: ${{ inputs.version_name }}
          CHANGELOG: ${{ inputs.changelog }}
          VERSION_TYPE: ${{ inputs.version_type }}
