name: Release
on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - working-directory: voxel/
        run: curl -o voxelmap-1.18.2-1.11.1.jar https://cdn.discordapp.com/attachments/931521967385878559/947927139330715668/voxelmap-1.18.2-1.11.1.jar
      - run: "./gradlew build :forge:modrinth :quilt:modrinth --no-daemon"
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
