name: Release
on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - run: "./gradlew build :forge:modrinth :fabric:modrinth --no-daemon"
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          SNAPSHOT: ""
