name: Release
on: [ workflow_dispatch ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
          arguments: forge:modrinth quilt:modrinth
          cache-read-only: ${{ github.repository_owner != 'emmods' }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
