name: Snapshot Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - run: ./gradlew publish --no-daemon
        env:
          MAVEN_URL: "https://maven.waffle.coffee/snapshots"
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
          SNAPSHOT: "-SNAPSHOT"
